apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres-deployment
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-deployment
    spec:
      containers:
      - image: postgres:15
        name: postgres
        resources: {}
        envFrom: # Esto importa todo el ConfigMap
      - configMapRef:
        name: postgres-config
      env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: password
      status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-deployment
  name: postgres-deployment
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-deployment
  type: ClusterIP
status:
  loadBalancer: {}
